In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [6]:
matrix = np.random.randint(1, 11, (5, 5))
print(matrix)

[[ 4  9  5  2  4]
 [ 4  7  6  7  4]
 [ 1  6 10  4  9]
 [ 4  2  2  6 10]
 [ 6  5  5  6  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [9]:
matrix = np.random.random((4, 4))
print(matrix)

[[0.17285865 0.3120377  0.88746407 0.07896456]
 [0.54509889 0.4801389  0.1700653  0.82531379]
 [0.3592042  0.10476018 0.74450961 0.64681271]
 [0.9710852  0.72365153 0.8867915  0.35892745]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [11]:
vector_1 = np.random.randint(1, 11, 5)
vector_2 = np.random.randint(1, 11, 5)
print(f"vector 1: {vector_1}")
print(f"vector 2: {vector_2}")

vector_1 = vector_1 + 3
vector_2 = vector_2 - 2
print(f"vector 1: {vector_1}")
print(f"vector 2: {vector_2}")

vector_1 = vector_1 * 2
vector_2 = vector_2 * 4
print(f"vector 1: {vector_1}")
print(f"vector 2: {vector_2}")


vector 1: [ 7  8 10  9  5]
vector 2: [ 1  6  5  9 10]
vector 1: [10 11 13 12  8]
vector 2: [-1  4  3  7  8]
vector 1: [20 22 26 24 16]
vector 2: [-4 16 12 28 32]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [13]:
vector_1 = np.random.randint(1, 100, 7)
vector_2 = np.random.randint(1, 100, 7)
scalar_product = np.dot(vector_1, vector_2)
print(scalar_product)

10698


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [15]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))
matrix = np.dot(matrix_1, matrix_2)
print(matrix)

[[112  52  60]
 [154 102  66]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [16]:
matrix = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[ 0.32352941 -0.85294118  0.38235294]
 [ 0.20588235 -0.08823529 -0.02941176]
 [-0.38235294  0.73529412 -0.08823529]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [20]:
matrix = np.random.random((4, 4))
matrix_transposition = matrix.T

print(matrix_transposition)

[[0.37365754 0.86680135 0.21399266 0.49077712]
 [0.09837222 0.85679101 0.31999689 0.96047379]
 [0.28708641 0.05429646 0.164442   0.62288339]
 [0.047856   0.31620163 0.35043082 0.97449219]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [21]:
matrix = np.random.randint(1, 11, ((3, 4)))
vector = np.random.randint(1, 11, 4)
result = np.dot(matrix, vector)
print(result)

[ 90  83 108]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [23]:
matrix = np.random.random((2, 3))
vector = np.random.random(3)
result = np.dot(matrix, vector)
print(result)

[1.05010953 0.74673508]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [26]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))
matrix_product = matrix_1 * matrix_2
print(matrix_product)

[[21 18]
 [ 6  4]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [27]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))
matrix_product = np.dot(matrix_1, matrix_2)
print(matrix_product)

[[ 56  32]
 [110  70]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [29]:
matrix = np.random.randint(1, 101, (5, 5))
total_sum = matrix.sum()
print(total_sum)

1234


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [32]:
matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))
matrix_product = np.subtract(matrix_1, matrix_2)
print(matrix_product)

[[-6  2 -6 -2]
 [-1 -3  2 -5]
 [ 5 -3 -6 -1]
 [ 0 -5  9  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix = np.random.random((3, 3))
vector = matrix.sum(axis=1).reshape(-1, 1)
print(vector)

[[0.85117039 0.1077236  0.80517797]
 [0.87359001 0.23963104 0.96620367]
 [0.96775077 0.66483657 0.14323541]]
[[1.76407196]
 [2.07942472]
 [1.77582275]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix = np.random.randint(1, 101, (3, 4))
matrix_product = matrix ** 2
print(matrix_product)

[[34 45 23 64]
 [23 57 94 49]
 [19 99 81 65]]
[[1156 2025  529 4096]
 [ 529 3249 8836 2401]
 [ 361 9801 6561 4225]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector = np.random.randint(1, 51, 4)
result = np.sqrt(vector)
print(result)

[50  8  4 41]
[7.07106781 2.82842712 2.         6.40312424]
