In [1]:
# Додавання/віднімання скаляра та вектора
import numpy as np

a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a + 2)
print(a - 1)

[3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4.]


In [2]:
# Множення на скаляр
a = np.array([1, 2, 3, 4, 5], dtype=float)
b = 5 * a
print(b)

[ 5. 10. 15. 20. 25.]


In [3]:
# Додавання/віднімання двох векторів
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)

[5 7 9]
[-3 -3 -3]


In [4]:
# Скалярний добуток
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a * b)
print(a / b)

print(np.dot(a, b))

[ 4 10 18]
[0.25 0.4  0.5 ]
32


In [5]:
# Матриці
m = np.array([[1, 2, 3],
              [4, 5, 6]],
              dtype=int)
print(m)

[[1 2 3]
 [4 5 6]]


In [6]:
# Розмірність матриці
a = np.array([1, 2, 3, 4, 5], dtype=float)
print(a.shape)

m = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print(m.shape)

(5,)
(2, 3)


In [7]:
# Множення матриць
a = np.array([[2, 3, 4, 5],
              [1, 2, 3, 4]])
b = np.array([[2, 2, 2, 2],
              [1, 1, 1, 1]])

print(a * b)

a = np.array([[1, 2, 3],
              [0, 1, 2]])
b = np.array([[1, 2],
              [0, 4],
              [-1, 0]])

c = np.dot(a, b)
print(c)

[[ 4  6  8 10]
 [ 1  2  3  4]]
[[-2 10]
 [-2  4]]


In [8]:
# Транспонування та зміна форми матриць в numpy
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
b = a.T
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
# Зміна розмірності матриці
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = a.reshape((3, 2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# Перетворення матриці в плоский вектор
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


In [11]:
# Одиночна матриця
a = np.eye(4, k=-1, dtype=float)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [12]:
# Обернена матриця
a = np.array([[1, 0, 3],
              [-1, -1, 2],
              [4, 7, 2]])

a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.64 -0.84 -0.12]
 [-0.4   0.4   0.2 ]
 [ 0.12  0.28  0.04]]


In [13]:
# Створення матриця із одиниць
a = np.ones((5,), dtype=float)
print(a)

b = np.ones((2, 3), dtype=int)
print(b)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [14]:
# Створення вектора або матриці з нулів
a = np.zeros(5, dtype=float)
print(a)

b = np.zeros((2, 3), dtype=int)
print(b)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]


In [15]:
# Створення масиві послідовних чисел
a = np.arange(5)
b = np.arange(1, 3, 0.5)

print(a)
print(b)

[0 1 2 3 4]
[1.  1.5 2.  2.5]


In [16]:
# Створення маасиву послідовних елементів, включаючи останній
a = np.linspace(1, 5, num=5)
b = np.linspace(1, 3, num=3)
print(a)
print(b)

[1. 2. 3. 4. 5.]
[1. 2. 3.]


In [17]:
# Створення масивів і матриць з випадковими числами
a = np.random.random(3)
b = np.random.random((3, 3))
print(a)
print(b)

[0.38327371 0.10574034 0.04414314]
[[0.10976293 0.41249498 0.83230941]
 [0.84805737 0.52913376 0.41146856]
 [0.92800016 0.65181586 0.19302202]]


In [18]:
# Індексація
a = np.array([1, 2, 3, 4, 5])
print(a[0])
print(a[1:])
print(a[:2])

1
[2 3 4 5]
[1 2]


In [19]:
# Індексація багатовимірного масиву
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


In [20]:
# Агрегування в NumPy (масив)
a = np.array([1, 2, 3, 4, 5])
print(a.min())
print(a.max())
print(a.sum())
print(int(a.mean()))
print(a.prod())

1
5
15
3
120


In [21]:
# Агругування в NumPy(матриця)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.min())
print(a.max())
print(a.sum())
print(int(a.mean()))
print(a.prod())

1
9
45
5
362880
